### ISSUE TITLE
Synchronizing the time on the video

### ISSUE THREAD

**Issue by philipsTanoto** [isonic1/flick#12]
Currently the video produced for iOS is displaying 1 photo per second, meaning if I set it to take a photo every 0.5 seconds, I would have a 2 seconds video per 1 second length of the actual recording. This would get even longer if I set it to take a photo every 0.2 seconds and a so on.

It would be great if I can have a video with the correct time length to the actual recording too. Is there any way I can do this?

**Comment by isonic1** [comment]
@philipsTanoto unfortunately it depends on the machine and device performance. The best I've seen for iOS devices is 2 screenshots per second. If you need good video quality, you can try this library: https://github.com/WPO-Foundation/xrecord . Flick was made for automated testing so the quality didn't really matter so much to me. Though, I might incorporate what xrecord did into flick when I have time, which I never do. ;) Pull requests are highly welcome if you want to contribute! :)

**Comment by philipsTanoto** [comment]
@isonic1 thanks for the suggestion! I'm also using flick for automated testing, but I'm finding it hard to view the video sometimes because I cannot really pin-point the exact time frame of when an error occurred due to the length on the video not matching. 
The video frames is also jumbled if it went beyond the limit that was set (e.g. 6000 screenshots). 
I'll give https://github.com/WPO-Foundation/xrecord a try.
