### ISSUE TITLE
Facing conflict while using Flick start video

### ISSUE THREAD

**Issue by BhaskarVj** [isonic1/flick#14]
Hi,

After successful installation of Flick when I place this "**flick video -a start -p ios**" command, I'm getting the below statements.
"Starting Screenshot Recorder...
Process will start after 500 screenshots."

Here, I'm not getting any video recorded under "/Users/myUserName/.flick". Could you please let me know whether this command is enough or it needs additional setup.

Thanks & Regards,
Vijay Bhaskar.

**Comment by isonic1** [comment]
Hi @BhaskarVj,

Run this ```brew uninstall --ignore-dependencies libimobiledevice && brew install --HEAD libimobiledevice``` and then make sure you can pair your device ```idevicepair pair``` and then validate ```idevicepair validate```.

See here: https://github.com/appium/appium/issues/6597#issuecomment-247038942

I'll add a check in Flick to make sure pairing is enabled before starting.

**Comment by BhaskarVj** [comment]
Hi @isonic1 ,

Firstly, thanks for your valuable suggestions. I've just done with all the setup you've mentioned above. And also I can be able to pair and validate my iOS device.
But still I'm not getting recorded video after start and stop commands. I'm getting below statements while doing start and stop:
**Start:**
"Starting Screenshot Recorder...
Process will start after 500 screenshots."

**Stop:**
Waiting for videofile.mp4 to exist...
error: No such file or directory.

Please suggest !!

Thanks & Regards,
Vijay Bhaskar.

**Comment by isonic1** [comment]
hmm, that is odd then if you're device is paired. can you do a ```flick screenshot -p ios``` and see if it generates a screenshot for you?

**Comment by BhaskarVj** [comment]
Yes, while doing this "**flick screenshot -p ios**" it is giving me every time the following statement in terminal.
**Saving to /Users/MyUserName/.flick/myPhoneUdid.png**
But when I navigate to the given location (.flick file folder), not even single image/file it has.

Please suggest !!

Thanks & Regards,
Vijay Bhaskar.

**Comment by isonic1** [comment]
Hmm, doesn't make sense if you're phone is paired to your machine. When you run ``` idevice_id -l``` you can see your phone UUID appear in the terminal? By default, flick will put the image or video in the directory you run the command from. So in your case above you must have been in the .flick dir when you executed flick screenshot. 

At the core of it the flick logic is using idevicescreenshot to make the screenshots. Does ```idevicescreenshot -u <your udid> <dir-path/test.png``` work for you?

**Comment by isonic1** [comment]
Have you also tried uninstalling and reinstalling the flick gem? ```gem uninstall flick``` then ```gem install flick```

**Comment by BhaskarVj** [comment]
Thanks for your reply!!
Yeah, when I run this "**idevice_id -l**" command it will generate device UDID in general and in my case too.
I'll do uninstall & installations of flick once again and will let you if it works or not.

Thanks & Regards,
Vijay Bhaskar.

**Comment by isonic1** [comment]
I assume it is working for you now so I am closing this. Let me know if ```idevicescreenshot -u <your udid> <dir-path/test.png``` works but flick doesn't and I'll reopen. If idevicescreenshot doesn't work for you either please search google for solutions to fixing that. Thanks.

**Comment by BhaskarVj** [comment]
Hi @isonic1,

firstly, sorry for the delay. I was working on other tasks. 
when I do this **"idevicescreenshot -u <my udid> <dir-path/test.png"** , I'm getting below error message:
Could not start screenshotr service! Remember that you have to mount the Developer disk image on your device if you want to use the screenshotr service. 

Could you please advice how to mount Developer disk image on device. I've tried by looking at suggestions but no luck.

Thanks & Regards,
Vijay Bhaskar.

**Comment by saikrishna321** [comment]
go to xcode -> devices you will see a yellow mark against your real device , wait for the xcode to mount n then try the idevice command

**Comment by isonic1** [comment]
Thanks once again @saikrishna321! Yes, @BhaskarVj please follow the advice @saikrishna321 gave.

**Comment by BhaskarVj** [comment]
Hi @saikrishna321 ,

I've waited till few hours time. One iOS device is having yellow mark and other doesn't have.

After lot tries.. again I'm facing the same issue.

when I do this "idevicescreenshot -u <dir-path/test.png" , I'm getting below error message:
**Could not start screenshotr service! Remember that you have to mount the Developer disk image on your device if you want to use the screenshotr service.**

Thanks & Regards,
Vijay Bhaskar.

**Comment by saikrishna321** [comment]
@BhaskarVj make sure you provide the right udid which is mounted as idevicescreenshot -u udidID pathtopng can you please tell whats your xcode version and the ios version ?

**Comment by BhaskarVj** [comment]
Yes, I've provided respected device's udid. 
iOS version : 9.3.2
Xcode version: 6.2

Thanks & Regards,
Vijay Bhaskar.

**Comment by saikrishna321** [comment]
@BhaskarVj can you pls update your xcode to 7.3.1 n give it a try
