### ISSUE TITLE
Option for disabling screenshot-based restriction for video recording

### ISSUE THREAD

**Issue by sskorol** [isonic1/flick#16]
@isonic1 hi,

Is there any way for stopping video recording only by sending `stop` command, ignoring the total amount of screenshots?

If my test is quite long, I can't predict max amount of screenshots, and recording stops until test is finished.

**Comment by isonic1** [comment]
Yeah, you can increase the screenshot count by passing ```-c 1000``` for a thousand. By default it's set at 500. Also, you can see all the available arguments for each job by passing the ```--help```. e.g. ```flick video --help```. Hope this helps.

**Comment by sskorol** [comment]
@isonic1 yeap, seems to be working fine. I was just a bit confused about video length, which was < real test execution time. Then I noticed a comment about unique screenshots mode.
