### ISSUE TITLE
Flick Jar File & Sample Java Code to capture recording IOS & Android

### ISSUE THREAD

**Issue by rsudam** [isonic1/flick#24]
It would be helpful for Java community to include sample programme to demonstrate Flick recording capabilities. I searched your account for Jar file & Sample Java code but somehow I couldn't able to find one.

**Comment by rsudam** [comment]
Figured out to work without Jar File & Java code.

**Comment by isonic1** [comment]
Hi @rsudam - would you mind posting your solution. Might be helpful for others looking for the same thing. Thanks.

**Comment by rsudam** [comment]
Sure, I have created two .sh files with below commands and running in via runtime.exec method available in java
startVideoRecoding.sh
`#!/bin/bash
cd ~
/usr/local/bin/flick video -a start -p ios -c 1000`

stopVideoRecording.sh
`#!/bin/bash
cd ~
flick video -a stop -p ios -o ./Documents -n newVideo1 -f mp4`

but when ever I tried running the code I'm getting below error. 

`[1;31m
idevice_id was not found. Please ensure you have installed idevice_id and it's in your $PATH
[0m`

I have done following things, but no use. I suspect that it is running in different location. 

`brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller`

**Comment by swarnimdixit** [comment]
flick video -a start -p ios -o /Users/shubham_v/Documents/workspace/IOS-Testing-Framework-For-Single-device/RecVideo -n Myvideo -u cadbfa009236b43083441e55446476be41a91a

like this u have to mention the device id
