### ISSUE TITLE
Micromax AQ4501 + 6.0.1 video recording is not working

### ISSUE THREAD

**Issue by vikramvi** [isonic1/flick#27]
Recording on this particular device doesn't work

```
adb shell
shell@AQ4501_sprout:/ $ cd sdcard/flick                                        
/system/bin/sh: cd: /sdcard/flick: No such file or directory
2|shell@AQ4501_sprout:/ $ cd sdcard
/system/bin/sh: cd: /sdcard: No such file or directory
```

`flick video -a stop -p android `

shows message **Stopping Recorder!!!**

It will nice to throw error couldn't perform recording on this device.

Please review

**Comment by vikramvi** [comment]
for this particular device` ls -ls ` after `adb shell `

has got below entry 

`lrwxrwxrwx root     root              2017-07-17 10:45 sdcard -> /storage/self/primary`

**Comment by saikrishna321** [comment]
you don't have to run flick inside the device .... do gem install flick on your machine and then run it against the decide udid

**Comment by vikramvi** [comment]
@saikrishna321 Yes, but some android devices don't have this particular directory and it fails as mentioned in original description. In that case user should be informed about it

**Comment by isonic1** [comment]
I added a temporary fix for this. Flick will just abort the run if the device is non-readable. I don't have time to come up with a more elaborate solution right now.
