### ISSUE TITLE
Recorded Video Frame Rate is wrong

### ISSUE THREAD

**Issue by erdoganonur** [isonic1/flick#29]
https://github.com/isonic1/flick/blob/6cd7a31d6ae2b8c6831bc3c92eb200eb1b725bdf/lib/flick/video.rb#L146

Even if we change the duration of the screen capture interval, the fps is always 1. So the time actually spent in the recorded video will never be the same.

**Comment by isonic1** [comment]
Yeah, you're right. This has been this way from the start. I added an argument to set the desired frame rate or defaults to 1 as it was before. 

flick video -p android -a stop --rate 5

**Comment by erdoganonur** [comment]
Thanx, but the screenshots has irregular interval, so you cannot determine fps constantly. I think, it would be perfect if it was automatically calculated. I'll send you pull request.
