### ISSUE TITLE
[Android O] flick crashing

### ISSUE THREAD

**Issue by alter-al** [isonic1/flick#31]
**Environment:**
- Pixel (Android O)
- flick 0.4.0 (on 0.3.6 no crash, but working not correctly)
- sierra 10.12.6

**Steps:**
1. run flick on Android O (example _flick log -p android -n test -a start_)

**Actual result:**
- crash:

mkdir: 'sdcard/flick': File exists
/usr/local/lib/ruby/gems/2.4.0/gems/flick-0.4.0/lib/flick/android.rb:30:in `create_flick_dirs': undefined method `strip' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/flick-0.4.0/lib/flick/android.rb:20:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/flick-0.4.0/lib/flick/video.rb:15:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/flick-0.4.0/lib/flick/video.rb:15:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/flick-0.4.0/bin/flick:33:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/flick-0.4.0/bin/flick:33:in `block (2 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by isonic1** [comment]
Thank you for reporting this @alter-al! It's fixed now. Latest gem version 0.4.1

**Comment by alter-al** [comment]
@isonic1, thanks! 
`flick log` working on Android O now.
But in 0.4.1, such as 0.3.6, log on Android O working not correctly.

Flick "grep" only system log, but not logcat <your_app> log.
I seeing debug log of my app on Android O via `adb logcat`, but not seeing it via `flick log`
