### ISSUE TITLE
iPhoneX video recording results in empty file

### ISSUE THREAD

**Issue by workwelldone** [isonic1/flick#38]
Hi! Thank you so much for your product!  Video recording is working great on all our iphone and ipad devices, except the iPhoneX, which always results in a file of size 0.

Steps to recreate:
1.  Attach iPhoneX
2. `flick video -a start -p ios`
3. --> Notice it says Starting recording!!!
4. `flick video -a stop -p ios`
5. --> Notice it says Stopping recording!!!
6.  Inspect the file created.
7. --> Notice it is of size zero.

Note:
Quicktime successfully records video on the iPhoneX.
Screenshots with flick on iPhoneX, work as expected.

**Comment by workwelldone** [comment]
Some additional information:
I can record video on the iPhoneX with quicktime.
Screenshots with flick on iPhoneX, work as expected.

**Comment by arunku2x** [comment]
Hi,

Even I am facing the same issue. iOS screen recording working fine for other iPhone models but for iPhone X, I am seeing an empty file. No errors are thrown by flick tool.

Regards,
Arun

**Comment by aryalakshmi** [comment]
Hi ,

Same issue i am facing. Were you able to find a solution?

**Comment by workwelldone** [comment]
No, I did not find a solution.

**Comment by aryalakshmi** [comment]
Is there some other tool which you were able to use on iphoneX for screen record?

**Comment by workwelldone** [comment]
I was not able to find a solution for the real device, however ‘xcrun simctl io recordVideo’ works on the simulator.

**Comment by gdimitris** [comment]
@workwelldone @aryalakshmi @arunku2x This is fixed now, please update flick to 0.4.5

**Comment by isonic1** [comment]
Yes, this is fixed thanks to @gdimitris. Please update the gem and try running again. Closing this ticket.

**Comment by workwelldone** [comment]
Thank you!
