### ISSUE TITLE
Argument Error

### ISSUE THREAD

**Issue by pavankumar9** [isonic1/flick#4]
I am getting below error , please help!

pavans-MacBook-Pro:screen_recording pavan$ flick -t video -a start -p android -u 192.168.56.101:5555 -c 3000
/Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/lib/flick/checker.rb:5: warning: Insecure world writable dir /usr/local in PATH, mode 040777

Starting Recoder!!!
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:128:in `initialize': wrong number of arguments (0 for 1+) (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/lib/flick/simple_daemon.rb:85:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/lib/flick/simple_daemon.rb:85:in `daemonize!'
	from /Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/lib/flick/video.rb:69:in `start_record'
	from /Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/lib/flick/video.rb:45:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/lib/flick/video.rb:33:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/flick-0.2.0/bin/flick:32:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by isonic1** [comment]
Hi @pavankumar9 thank you for reporting this. I'm working on a fix and will have it out shortly. Thanks.

**Comment by isonic1** [comment]
This is fixed now @pavankumar9. Please do a "gem update flick" and try again. Thank you for reporting it.
