### ISSUE TITLE
Unable to record > 3 minutes video with android device

### ISSUE THREAD

**Issue by vladsobol** [isonic1/flick#40]
I am having issue with recording video of android real devices and simulators > 3 min.
After running command "flick video -a start -p android -e true" the recording starts and in console I see that it is in extended mode but after stopping video recording "flick video stop -p android -o /Descktop/record" I see that video file is saved but duration of video  3 minutes.
Please suggest a solution.

**Comment by varunsaran1** [comment]
Facing the same issue on android 7 and android8 physical devices

**Comment by isonic1** [comment]
This is fixed now thanks to @gdimitris. Please update the gem to 0.4.6.

Run in extended mode: ```flick video -p android -e true -a start```
