### ISSUE TITLE
Size of video is Zero bytes after saving for iPhone device

### ISSUE THREAD

**Issue by sainiketan47** [isonic1/flick#9]
The video is saved on home path but size of video is 0 bytes. It is also capturing the screenshots at path: User/xyz/.flick/UDID but after stop video command i.e 
flick video -a stop -p ios -o $HOME -n myVideo -f mp4 
Saved video size is zero bytes.
https://postimg.org/image/ob996v49n/

**Comment by isonic1** [comment]
@sainiketan47 can you run the stop command with trace? e.g "flick video -a stop -p ios -o $HOME -n myVideo -f mp4 --trace". Then paste the whole output to this ticket? Thanks.

**Comment by isonic1** [comment]
@sainiketan47 please see the issue below and follow the steps to reinstall ideviceinstaller. 

https://github.com/isonic1/flick/issues/10

**Comment by isonic1** [comment]
Setting to wontfix. If the steps in issue #10 dont resolve this then I will reopen. Thanks for reporting.
